export const ActionTypes = {
  SHOW_DATA: "SHOW_DATA",
  SHOW_LOADING_PIECHART: "SHOW_LOADING_PIECHART",
  HIDE_LOADING_PIECHART: "HIDE_LOADING_PIECHART",
  GET_DATA_BAR: "GET_DATA_BAR",
  SHOW_LOADING_BARCHART: "SHOW_LOADING_BARCHART",
  HIDE_LOADING_BARCHART: "HIDE_LOADING_BARCHART"
};


