export const ActionTypes = {
  SHOW_DATA: "SHOW_DATA",
  SHOW_LOADING_PIECHART: "SHOW_LOADING_PIECHART",
  HIDE_LOADING_PIECHART: "HIDE_LOADING_PIECHART",
  GET_DATA_BAR: "GET_DATA_BAR",
  SHOW_LOADING_BARCHART: "SHOW_LOADING_BARCHART",
  HIDE_LOADING_BARCHART: "HIDE_LOADING_BARCHART",
  GET_DATA_HEATCHART: "GET_DATA_HEATCHART",
  SHOW_LOADING_HEATCHART: "SHOW_LOADING_HEATCHART",
  HIDE_LOADING_HEATCHART: "HIDE_LOADING_HEATCHART",
  SET_DATE: "SET_DATE",
};


